name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Run the tests for the code
        run: go test ./... -cover

  style:
    name: Style 
    runs-on: ubuntu-latest

    steps:
      - name: check out code 
        uses: actions/checkout@v4

      - name: Set up Go 
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
      
      - name: Run the tests for formatting
        run: test -z $(go fmt ./...)